name: Build artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    - name: Test changes
      run: npx nx affected --target=test --base=main~1 --head=main
    - name: Build changes
      run: npx nx affected --target=build --base=main~1 --head=main
    - name: Deploy changes
      run: npx nx affected --target=deploy --base=main~1 --head=main
